## Numpy
- 一个开源的科学计算库
- 可以方便实用数组，矩阵运算
- 包含线性代数，傅里叶变换，随机数生成等大量函数

In [2]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

### Numpy创建数组
```
np.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
```

- object	数组或嵌套的数列
- dtype	数组元素的数据类型，可选
- copy	对象是否需要复制，可选
- order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
- subok	默认返回一个与基类类型一致的数组
- ndmin	指定生成数组的最小维度


In [3]:
# array()函数，括号内可以是列表、元组、数组、迭代对象
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
# 元组
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [5]:
# 数组
a = np.array([1,2,3,4,5])
np.array(a)

array([1, 2, 3, 4, 5])

In [6]:
# 迭代对象
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 生成器
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
np.array([i for i in range(10) if i%2==0])

array([0, 2, 4, 6, 8])

In [10]:
# 列表中元素类型不同
np.array([1,1.2,3,4,"5"])

array(['1', '1.2', '3', '4', '5'], dtype='<U32')

In [12]:
# 二维数组嵌套
ar = np.array([
    [1,2,3],
    ('a','b','c')
])
ar

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U21')

In [14]:
ar2 = np.array([
    [1,2,3],
    ('a','b','c','d')
])
ar2

/home/dldx/anaconda3/envs/torch/lib/python3.7/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


array([list([1, 2, 3]), ('a', 'b', 'c', 'd')], dtype=object)

In [15]:
ar2.shape

(2,)

In [16]:
ar2.ndim

1

In [17]:
# 设置元素类型
a = np.array([1,2,3,4], dtype = 'float')
a

array([1., 2., 3., 4.])

In [20]:
a = np.array([1,2,3,4])
b = np.array(a)
print("a.id:", id(a))
print("b.id:", id(b))

a.id: 140621726100816
b.id: 140621726100720


In [21]:
a = np.array([1,2,3,4])
b = a
print("a.id:", id(a))
print("b.id:", id(b))

a.id: 140621726118512
b.id: 140621726118512


In [24]:
a = np.array([1,2,3,4], ndmin=2)
a

array([[1, 2, 3, 4]])

### numpy.arange(start, stop, step, dtype)
-  start	起始值，默认为0
- stop	终止值（不包含）
- step	步长，默认为1
- dtype	返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(3.1)

array([0., 1., 2., 3.])

In [ ]:
# range(3.2)会报错

In [8]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [9]:
np.arange(20,3)

array([], dtype=int64)

In [3]:
np.arange(0,200,3)

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198])

### numpy.linspace
numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的
```
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```
- start	序列的起始值
- stop	序列的终止值，如果endpoint为true，该值包含于数列中
- num	要生成的等步长的样本数量，默认为50
- endpoint	该值为 true 时，数列中包含stop值，反之不包含，默认是True。
- retstep	如果为 True 时，生成的数组中会显示间距，反之不显示。
- dtype	ndarray 的数据类型

In [5]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### numpy.logspace
numpy.logspace 函数用于创建一个于等比数列
```
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```
- start	序列的起始值为：base ** start
- stop	序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
- num	要生成的等步长的样本数量，默认为50
- endpoint	该值为 true 时，数列中中包含stop值，反之不包含，默认是True。
- base	对数 log 的底数。
- dtype	ndarray 的数据类型

## Numpy数组属性
- ndarray.ndim	秩，即轴的数量或维度的数量
- ndarray.shape	数组的维度，对于矩阵，n 行 m 列
- ndarray.size	数组元素的总个数，相当于 .shape 中 n*m 的值
- ndarray.dtype	ndarray 对象的元素类型
- ndarray.itemsize	ndarray 对象中每个元素的大小，以字节为单位
- ndarray.flags	ndarray 对象的内存信息
- ndarray.real	ndarray元素的实部
- ndarray.imag	ndarray 元素的虚部
- ndarray.data	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。